# Build configure for https://www.tea-ci.org (fork of Drone CI with Msys2 support)
build:
  image: teaci/msys32
  shell: mingw32
  pull: true
  branches:
    -master
  environment:
    - SUBTARGET=tiny
    - MINGW32=/c/msys32/mingw32
    - MAME_EXE=mametiny.exe
#    - SOURCES=src/mame/drivers/pacman.cpp
  commands:
     - echo Passed test && true
#    - make
#    - ./$MAME_EXE -validate && echo "Validation successful"

notify:
  irc:
    prefix: build-ppriest
    nick: $$IRC_USER
    channel: ppriest
    server:
      host: $$IRC_HOST
      port: $$IRC_PORT
      password: $$IRC_PASS
      tls: true
    when:
      success: false
      failure: true
      change: true
  
  email:
    from: tourniquet@gmx.net
    host: $$EMAIL_SERVER
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASSWORD
    recipients:
      - ppriest@gmail.com
    when:
      success: false
      failure: true
      change: true
