# Build configure for https://www.tea-ci.org (fork of Drone CI with Msys2 support)
build:
  image: teaci/msys32
  shell: mingw32
  pull: true
  branches:
    -master
  environment:
    - SUBTARGET=tiny
    - MINGW32=/c/msys32/mingw32
    - MAME_EXE=mametiny.exe
    - SOURCES=src/mame/drivers/pacman.cpp
  commands:
    - pacman -S winpty
    - winpty echo testing winpty
#    - make && echo before validate && winpty ./$MAME_EXE -validate
  
notify:
  email:
    from: ppriest@gmail.com
    host: $$EMAIL_SERVER
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASSWORD
    recipients:
      - ppriest@gmail.com
    when:
      success: false
      failure: false
      change: true
