# Build configure for https://www.tea-ci.org (fork of Drone CI with Msys2 support)
build:
  image: teaci/msys64
  shell: mingw64
  pull: true
  branches:
    -master
  environment:
    - SUBTARGET=tiny
    - MINGW64=/c/msys64/mingw64
    - MAME_EXE=mametiny64.exe
  commands:
    - echo foo && echo "$MAME_EXE" && echo bar
    - echo echo foo2 > echo.sh
    - chmod a+x echo.sh
    - echo foo1 && ./echo.sh -validate
  
notify:
  email:
    from: tourniquet@gmx.net
    host: $$EMAIL_SERVER
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASSWORD
    recipients:
      - ppriest@gmail.com
    when:
      success: false
      failure: false
      change: true
